apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: team-a-database
spec:
  storageClassName: localblock
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi